//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PitStop
{
    public partial class AdvisorDashboard
    {
        /// <summary>Displays the logged-in advisor's username.</summary>
        protected global::System.Web.UI.WebControls.Label lblAdvisorName;

        /// <summary>Displays the total number of registered students.</summary>
        protected global::System.Web.UI.WebControls.Label lblStudentCount;

        /// <summary>Shows the 5 most recently registered students.</summary>
        protected global::System.Web.UI.WebControls.GridView gvRecentStudents;
    }
}
